apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: contextforge-postgres-values
  namespace: infra-postgres-operations
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infra-postgres-operations-openbao-secret-store
    kind: SecretStore
  target:
    name: contextforge-postgres-values
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: password
      remoteRef:
        key: infra-postgres-operations/internal
        property: contextforgePassword
