{{- $secrets := .Values.frontendLibrechatSecrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: frontend-librechat-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "frontend-librechat-shared.labels" . | nindent 4 }}
type: Opaque
stringData:
  CODEAPI_JWT_PRIVATE_KEY: {{ $secrets.codeInterpreterJwtPrivateKey | quote }}
  CREDS_IV: {{ $secrets.credsIv | quote }}
  CREDS_KEY: {{ $secrets.credsKey | quote }}
  DOMAIN_CLIENT: {{ printf "https://%s" .Values.frontendLibrechat.hostname | quote }}
  DOMAIN_SERVER: {{ printf "https://%s" .Values.frontendLibrechat.hostname | quote }}
  JWT_REFRESH_SECRET: {{ $secrets.jwtRefreshSecret | quote }}
  JWT_SECRET: {{ $secrets.jwtSecret | quote }}
  MEILI_MASTER_KEY: {{ $secrets.meiliMasterKey | quote }}
  MONGO_URI: {{ printf "mongodb://%s:%s@%s:%v/%s?authSource=%s&authMechanism=%s&tls=true&tlsCAFile=%s&directConnection=%v" ($secrets.documentdbUser | urlquery) ($secrets.documentdbPassword | urlquery) .Values.frontendLibrechat.documentdb.host .Values.frontendLibrechat.documentdb.port (.Values.frontendLibrechat.documentdb.database | urlquery) (.Values.frontendLibrechat.documentdb.authSource | urlquery) (.Values.frontendLibrechat.documentdb.authMechanism | urlquery) (.Values.frontendLibrechat.documentdb.tls.caFile | urlquery) .Values.frontendLibrechat.documentdb.directConnection | quote }}
  OPENID_CLIENT_SECRET: {{ $secrets.openidClientSecret | quote }}
  OPENID_CLIENT_ID: {{ .Values.authKeycloak.librechatClientId | quote }}
  OPENID_ISSUER: {{ printf "https://%s/realms/%s" .Values.authKeycloak.hostname .Values.authKeycloak.realm | quote }}
  OPENID_SESSION_SECRET: {{ $secrets.openidSessionSecret | quote }}
  RAG_OPENAI_API_KEY: {{ $secrets.ragOpenaiApiKey | quote }}
  RAG_POSTGRES_PASSWORD: {{ $secrets.ragPostgresqlPassword | quote }}
  RAG_POSTGRES_USER: {{ $secrets.ragPostgresqlUser | quote }}
  REDIS_URI: {{ printf "redis://:%s@%s:%v/0" ($secrets.valkeyPassword | urlquery) .Values.frontendLibrechat.valkey.service.name .Values.frontendLibrechat.valkey.service.port | quote }}
  VALKEY_PASSWORD: {{ $secrets.valkeyPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: frontend-librechat-admin-panel-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "frontend-librechat-shared.labels" . | nindent 4 }}
type: Opaque
stringData:
  ADMIN_PANEL_METRICS_SECRET: {{ $secrets.adminPanelMetricsSecret | quote }}
  SESSION_SECRET: {{ $secrets.adminPanelSessionSecret | quote }}
