{{- $databasePassword := required "infraAgentgatewayWrapperSecrets.databasePassword is required" .Values.infraAgentgatewayWrapperSecrets.databasePassword -}}
apiVersion: v1
kind: Secret
metadata:
  name: infra-agentgateway-database-secret
  namespace: infra-agentgateway
  labels:
    app.kubernetes.io/name: request-log-database-credentials
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: infra-agentgateway
type: Opaque
stringData:
  password: {{ $databasePassword | quote }}
