apiVersion: v1
kind: ConfigMap
metadata:
  name: monitor-pii-engine-config-map
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitor-pii-engine.labels" . | nindent 4 }}
data:
  policy.yaml: |-
    {{- toYaml .Values.monitorPiiEngine.policy | nindent 4 }}
