apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.monitorPiiEngine.runtimeSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitor-pii-engine.labels" . | nindent 4 }}
type: Opaque
stringData:
  hash-key: {{ .Values.monitorPiiEngineSecrets.hashKey | default "" | quote }}
  encryption-key: {{ .Values.monitorPiiEngineSecrets.encryptionKey | default "" | quote }}
