apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitor-pii-engine-service-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitor-pii-engine.labels" . | nindent 4 }}
    release: monitor-kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pii-engine
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: management
      path: /metrics
      interval: 30s
