apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitor-pii-engine-valkey-primary
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitor-pii-engine.valkeyLabels" . | nindent 4 }}
automountServiceAccountToken: false
