apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: infra-reloader
spec:
  releaseName: infra-reloader
  targetNamespace: infra-reloader
  interval: 5m
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 1m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 1m
  chart:
    spec:
      chart: ./charts/reloader
      sourceRef:
        kind: GitRepository
        name: k8s-stack
        namespace: flux-system
      interval: 1m
