apiVersion: v1
kind: Service
metadata:
  name: frontend-dify-agent-backend-service
  namespace: frontend-dify
  labels:
    app.kubernetes.io/name: agent-backend
    app.kubernetes.io/instance: frontend-dify-agent
    app.kubernetes.io/part-of: frontend-dify
spec:
  selector:
    app.kubernetes.io/name: agent-backend
    app.kubernetes.io/instance: frontend-dify-agent
  ports:
    - name: http
      port: 5050
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-dify-agent-sandbox-service
  namespace: frontend-dify
  labels:
    app.kubernetes.io/name: agent-sandbox
    app.kubernetes.io/instance: frontend-dify-agent
    app.kubernetes.io/part-of: frontend-dify
spec:
  selector:
    app.kubernetes.io/name: agent-sandbox
    app.kubernetes.io/instance: frontend-dify-agent
  ports:
    - name: http
      port: 5004
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-dify-agent-proxy-service
  namespace: frontend-dify
  labels:
    app.kubernetes.io/name: agent-proxy
    app.kubernetes.io/instance: frontend-dify-agent
    app.kubernetes.io/part-of: frontend-dify
spec:
  selector:
    app.kubernetes.io/name: agent-proxy
    app.kubernetes.io/instance: frontend-dify-agent
  ports:
    - name: proxy
      port: 3128
      targetPort: proxy
