apiVersion: v2
name: frontend-librechat
description: First-party LibreChat UI and API workload
type: application
version: 1.2.2
appVersion: "v0.8.8-rc4"
annotations:
  source.commit: 361553f3322d7b9bb547d0a9c2c5aaefc2934901
  source.repository: https://github.com/danny-avila/LibreChat
