apiVersion: v2
name: frontend-librechat
description: First-party LibreChat UI and API workload
type: application
version: 1.1.0
appVersion: "eaed216994b2604e050966cd6eaf3c2bdd359233"
annotations:
  source.commit: eaed216994b2604e050966cd6eaf3c2bdd359233
  source.repository: https://github.com/danny-avila/LibreChat
