apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app.yaml
  - oidc.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: forgejo-app-defaults
    namespace: forgejo
    files:
      - values.yaml=app-defaults.yaml
