apiVersion: v1
kind: ConfigMap
metadata:
  name: monitor-fluent-bit-shared-opensearch-ca
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: fluent-bit-shared
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: monitor-fluent-bit
data: {}
