apiVersion: v1
kind: Service
metadata:
  name: {{ include "librechat-code-interpreter-egress-gateway.fullname" . }}
  labels:
    {{- include "librechat-code-interpreter-egress-gateway.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.frontendLibrechatCodeInterpreter.egressGateway.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "librechat-code-interpreter-egress-gateway.selectorLabels" . | nindent 4 }}
