apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "librechat-code-interpreter-egress-gateway.fullname" . }}
  labels:
    {{- include "librechat-code-interpreter-egress-gateway.labels" . | nindent 4 }}
automountServiceAccountToken: false
