apiVersion: v2
name: librechat-code-interpreter-shared
description: Shared secrets, durable storage, and network isolation for LibreChat Code Interpreter
type: application
version: 1.0.0
appVersion: "fea707467600f3802d65596a6875c7822f25cfd8"
annotations:
  source.commit: fea707467600f3802d65596a6875c7822f25cfd8
  source.repository: https://github.com/ClickHouse/code-interpreter
