apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frontend-librechat-meilisearch
  namespace: frontend-librechat
spec:
  releaseName: frontend-librechat-meilisearch
  interval: 5m
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 1m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 1m
  dependsOn:
    - name: frontend-librechat-shared
      namespace: frontend-librechat
    - name: rook-ceph
      namespace: infra-rook-ceph
  chart:
    spec:
      chart: ./charts/librechat/meilisearch
      sourceRef:
        kind: GitRepository
        name: k8s-stack
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: base-shared-hostnames-config-map
      valuesKey: values.yaml
    - kind: ConfigMap
      name: base-shared-resources-config-map
      valuesKey: values.yaml
    - kind: ConfigMap
      name: frontend-librechat-app-defaults
      valuesKey: values.yaml
    - kind: ConfigMap
      name: client-values
      valuesKey: values.yaml
    - kind: ConfigMap
      name: librechat-product-values
      valuesKey: values.yaml
