apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-dify-plugin-daemon-pvc
  namespace: frontend-dify
  labels:
    app.kubernetes.io/name: plugin-daemon
    app.kubernetes.io/instance: frontend-dify-plugin-daemon
    app.kubernetes.io/part-of: frontend-dify
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.frontendDify.storage.size }}
  storageClassName: {{ .Values.frontendDify.storage.storageClassName }}
