apiVersion: v1
kind: ServiceAccount
metadata:
  name: wireguard-external-secrets
  namespace: wireguard
automountServiceAccountToken: false
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: wireguard-openbao-secret-store
  namespace: wireguard
spec:
  provider:
    vault:
      server: https://infra-openbao.infra-openbao.svc:8200
      path: secret
      version: v2
      caProvider:
        type: ConfigMap
        name: infra-openbao-ca-bundle
        key: ca.crt
      auth:
        kubernetes:
          mountPath: kubernetes
          role: wireguard
          serviceAccountRef:
            name: wireguard-external-secrets
            audiences: [openbao]
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wireguard-server-key
  namespace: wireguard
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: wireguard-openbao-secret-store
    kind: SecretStore
  target:
    name: wireguard-server-key
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: privateKey
      remoteRef:
        key: wireguard/internal
        property: privateKey
