# =============================================================================
# ServiceAccount for the keycloak-api-key-bridge OIDC configuration Job
# =============================================================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-keycloak-keycloak-api-key-bridge-oidc-service-account
  namespace: auth-keycloak
  labels:
    app.kubernetes.io/name: keycloak-api-key-bridge-oidc
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: auth-keycloak
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
automountServiceAccountToken: false
