{{- if .Values.authKeycloak.activeDirectory.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-keycloak-active-directory-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: active-directory
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: auth-keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: auth-keycloak-openbao-secret-store
    kind: SecretStore
  target:
    name: auth-keycloak-active-directory-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: activeDirectoryBindDn
      remoteRef:
        key: auth-keycloak/external
        property: activeDirectoryBindDn
    - secretKey: activeDirectoryBindCredential
      remoteRef:
        key: auth-keycloak/external
        property: activeDirectoryBindCredential
{{- end }}
