apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-issuers-route53-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: cert-manager-issuers
    app.kubernetes.io/instance: infra-cert-manager-issuers
    app.kubernetes.io/part-of: infra-cert-manager
type: Opaque
stringData:
  access-key-id: {{ .Values.certManager.aws.accessKeyId
    | required "certManager.aws.accessKeyId is required" | quote }}
  secret-access-key: {{ .Values.certManager.aws.secretAccessKey
    | required "certManager.aws.secretAccessKey is required" | quote }}
