apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-studio-shared-opensearch-ca
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: studio-shared
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Namespace }}
data: {}
