apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: langfuse
  namespace: monitor-langfuse
spec:
  releaseName: monitor-langfuse
  interval: 5m
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 1m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 1m
  dependsOn:
    - name: traefik
      namespace: kube-system
    - name: cert-manager-issuers
      namespace: infra-cert-manager
    - name: rook-ceph
      namespace: infra-rook-ceph
    - name: postgres-operations
      namespace: infra-postgres-operations
  chart:
    spec:
      chart: ./charts/langfuse
      sourceRef:
        kind: GitRepository
        name: k8s-stack
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: base-shared-hostnames-config-map
      valuesKey: values.yaml
    - kind: ConfigMap
      name: base-shared-resources-config-map
      valuesKey: values.yaml
    - kind: ConfigMap
      name: monitor-langfuse-app-defaults
      valuesKey: values.yaml
    - kind: Secret
      name: monitor-langfuse-secrets
      valuesKey: values.yaml
    - kind: ConfigMap
      name: client-values
      valuesKey: values.yaml
    - kind: ConfigMap
      name: langfuse-product-values
      valuesKey: values.yaml
