apiVersion: v1
kind: Namespace
metadata:
  name: auth-keycloak
  labels:
    secrets.neurwerk.com/openbao-trust: "true"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: auth-keycloak
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
