apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-approval-policy
  namespace: infra-cert-manager
spec:
  releaseName: infra-cert-manager-approval-policy
  interval: 5m
  timeout: 15m
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 1m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 1m
  waitStrategy:
    name: poller
  healthCheckExprs:
    - apiVersion: policy.cert-manager.io/v1alpha1
      kind: CertificateRequestPolicy
      inProgress: status.conditions.filter(e, e.type == 'Ready').exists(e, e.status != 'True')
      current: status.conditions.filter(e, e.type == 'Ready').exists(e, e.status == 'True')
  dependsOn:
    - name: cert-manager-approver-policy
      namespace: infra-cert-manager
  chart:
    spec:
      chart: ./charts/cert-manager/approval-policy
      sourceRef:
        kind: GitRepository
        name: k8s-stack
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: client-values
      valuesKey: values.yaml
    - kind: ConfigMap
      name: cert-manager-product-values
      valuesKey: values.yaml
