apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "librechat-code-interpreter-file-server.fullname" . }}
  labels:
    {{- include "librechat-code-interpreter-file-server.labels" . | nindent 4 }}
automountServiceAccountToken: false
