apiVersion: v1
kind: Service
metadata:
  name: {{ include "librechat-code-interpreter-valkey.fullname" . }}
  labels:
    {{- include "librechat-code-interpreter-valkey.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: valkey
      port: {{ .Values.frontendLibrechatCodeInterpreter.valkey.service.port }}
      targetPort: valkey
      protocol: TCP
  selector:
    {{- include "librechat-code-interpreter-valkey.selectorLabels" . | nindent 4 }}
