apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: contextforge
resources:
  - contextforge.yaml
configMapGenerator:
  - name: contextforge-app-defaults
    files: [values.yaml=app-defaults.yaml]
generatorOptions:
  disableNameSuffixHash: true
