apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frontend-dify-redis
  namespace: frontend-dify
spec:
  releaseName: frontend-dify-redis
  interval: 5m
  timeout: 10m
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 1m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 1m
  dependsOn:
    - name: frontend-dify-shared
      namespace: frontend-dify
    - name: rook-ceph
      namespace: infra-rook-ceph
  chart:
    spec:
      chart: ./charts/dify/redis
      sourceRef:
        kind: GitRepository
        name: k8s-stack
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: base-shared-hostnames-config-map
      valuesKey: values.yaml
    - kind: ConfigMap
      name: base-shared-resources-config-map
      valuesKey: values.yaml
    - kind: ConfigMap
      name: base-shared-oidc-clients-config-map
      valuesKey: values.yaml
    - kind: ConfigMap
      name: frontend-dify-app-defaults
      valuesKey: values.yaml
    - kind: ConfigMap
      name: client-values
      valuesKey: values.yaml
    - kind: ConfigMap
      name: dify-product-values
      valuesKey: values.yaml
