apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frontend-studio
resources:
  - api.yaml
  - web.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: base-shared-hostnames-config-map
    files:
      - values.yaml=../shared/hostnames.yaml
  - name: base-shared-resources-config-map
    files:
      - values.yaml=../shared/resources.yaml
  - name: base-shared-oidc-clients-config-map
    files:
      - values.yaml=../shared/oidc-clients.yaml
