apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak-agentgateway-oidc
  namespace: auth-keycloak
spec:
  releaseName: auth-keycloak-agentgateway-oidc
  interval: 5m
  timeout: 15m
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 1m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 1m
  dependsOn:
    - name: keycloak
      namespace: auth-keycloak
  chart:
    spec:
      chart: ./charts/keycloak/oidc/agentgateway
      sourceRef:
        kind: GitRepository
        name: k8s-stack
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: base-shared-hostnames-config-map
      valuesKey: values.yaml
    - kind: ConfigMap
      name: base-shared-resources-config-map
      valuesKey: values.yaml
    - kind: ConfigMap
      name: base-shared-oidc-clients-config-map
      valuesKey: values.yaml
    - kind: ConfigMap
      name: auth-keycloak-app-defaults
      valuesKey: values.yaml
    - kind: ConfigMap
      name: client-openrouter-catalog-values
      valuesKey: values.yaml
      optional: true
    - kind: Secret
      name: auth-keycloak-secrets
      valuesKey: values.yaml
    - kind: ConfigMap
      name: client-values
      valuesKey: values.yaml
    - kind: ConfigMap
      name: keycloak-product-values
      valuesKey: values.yaml
