apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "librechat-admin-panel.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "librechat-admin-panel.labels" . | nindent 4 }}
automountServiceAccountToken: false
