apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: librechat-code-interpreter-default-deny
  labels:
    {{- include "librechat-code-interpreter-shared.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
