apiVersion: v1
kind: ServiceAccount
metadata:
  name: librechat-code-interpreter-package-init
  labels:
    {{- include "librechat-code-interpreter-shared.labels" . | nindent 4 }}
automountServiceAccountToken: false
