apiVersion: v2
name: frontend-librechat-shared
description: Shared runtime configuration and credentials for LibreChat components
type: application
version: 1.0.0
appVersion: "14d4f2789d8f1d308713f7acd98fab925f8aa74d"
annotations:
  source.commit: 14d4f2789d8f1d308713f7acd98fab925f8aa74d
  source.repository: https://github.com/danny-avila/LibreChat
