apiVersion: v2
name: frontend-librechat-shared
description: Shared runtime configuration and credentials for LibreChat components
type: application
version: 1.9.0
appVersion: "v0.8.8"
annotations:
  source.commit: e8f3be08623663d4ad7f7241e693c94469b63bb0
  source.repository: https://github.com/LibreChat-AI/LibreChat
