apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitor-opensearch-ca-recovery-service-account
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: ca-recovery
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: infra-cert-manager-opensearch-ca-recovery-source-role
  namespace: infra-cert-manager
  labels:
    app.kubernetes.io/name: ca-recovery
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: infra-cert-manager
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["monitor-opensearch-ca-bundle"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: infra-cert-manager-opensearch-ca-recovery-source-role-binding
  namespace: infra-cert-manager
  labels:
    app.kubernetes.io/name: ca-recovery
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: infra-cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: infra-cert-manager-opensearch-ca-recovery-source-role
subjects:
  - kind: ServiceAccount
    name: monitor-opensearch-ca-recovery-service-account
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: monitor-opensearch-ca-recovery-role
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: ca-recovery
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["monitor-opensearch-ca-trust"]
    verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitor-opensearch-ca-recovery-role-binding
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: ca-recovery
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: monitor-opensearch-ca-recovery-role
subjects:
  - kind: ServiceAccount
    name: monitor-opensearch-ca-recovery-service-account
    namespace: {{ .Release.Namespace }}
