apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: monitor-opensearch-archive-object-bucket-claim
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: opensearch-archive-object-bucket-claim
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Namespace }}
spec:
  bucketName: opensearch-archive
  storageClassName: infra-rook-ceph-object-bucket
  additionalConfig:
    bucketLifecycle: |
      {
        "Rules": [
          {
            "ID": "ExpireAfter90Days",
            "Status": "Enabled",
            "Prefix": "",
            "Expiration": {"Days": 90}
          }
        ]
      }
