apiVersion: apps/v1
kind: Deployment
metadata:
  name: ceph-csi-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: ceph-csi-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Namespace }}
    control-plane: controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ceph-csi-operator
      app.kubernetes.io/instance: {{ .Release.Name }}
      control-plane: ceph-csi-op-controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/name: ceph-csi-operator
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/part-of: {{ .Release.Namespace }}
        control-plane: ceph-csi-op-controller-manager
    spec:
      serviceAccountName: ceph-csi-controller-manager
      securityContext:
        runAsNonRoot: true
      containers:
        - name: manager
          image: {{ .Values.infraRookCeph.csiOperatorImage | quote }}
          command: ["/manager"]
          args: ["--leader-elect"]
          env:
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CSI_SERVICE_ACCOUNT_PREFIX
              value: ceph-csi-
            - name: WATCH_NAMESPACE
              value: ""
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - name: health
              containerPort: 8081
              protocol: TCP
          resources:
            {{- toYaml .Values.infraRookCeph.resources.csiOperator | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
      terminationGracePeriodSeconds: 10
