apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.infraRookCeph.blockStorage.openbaoStorageClassName }}
  labels:
    {{- include "infra-rook-ceph.labels" . | nindent 4 }}
    app.kubernetes.io/component: openbao-storage
provisioner: rook-ceph.rbd.csi.ceph.com
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  clusterID: {{ .Release.Namespace | quote }}
  pool: {{ .Values.infraRookCeph.blockStorage.poolName | quote }}
  imageFormat: "2"
  imageFeatures: layering
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: {{ .Release.Namespace }}
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
  csi.storage.k8s.io/node-stage-secret-namespace: {{ .Release.Namespace }}
  csi.storage.k8s.io/fstype: ext4
