{{- $namespace := .Release.Namespace -}}
{{- $manifest := .Files.Get "files/upstream/common-without-namespace.yaml" | replace "namespace: rook-ceph # namespace:operator" (printf "namespace: %s" $namespace) | replace "namespace: rook-ceph # namespace:cluster" (printf "namespace: %s" $namespace) -}}
{{ $manifest }}
