apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontend-studio-pii-engine-client-certificate
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: studio-api
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Namespace }}
spec:
  commonName: frontend-studio-api
  secretName: {{ .Values.frontendStudio.api.piiEngineClientSecretName }}
  privateKey:
    algorithm: RSA
    size: 2048
    encoding: PKCS8
    rotationPolicy: Always
  duration: 2160h
  renewBefore: 360h
  usages:
    - client auth
  issuerRef:
    name: infra-cert-manager-internal-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
