apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: monitor-agentgateway-extproc-image-inspection-secret
  namespace: monitor-agentgateway-extproc
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: monitor-agentgateway-extproc-openbao-secret-store
    kind: SecretStore
  target:
    name: monitor-agentgateway-extproc-image-inspection-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: api-key
      remoteRef:
        key: monitor-agentgateway-extproc/external
        property: apiKey
