{{- $adminPassword := required "postgresAuthSecrets.adminPassword is required" .Values.postgresAuthSecrets.adminPassword -}}
{{- $keycloakPassword := required "postgresAuthSecrets.keycloakPassword is required" .Values.postgresAuthSecrets.keycloakPassword -}}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-auth-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgres-auth.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: {{ $adminPassword | quote }}
  keycloak-password: {{ $keycloakPassword | quote }}
