apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgres-auth.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-auth-provisioning
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: postgres-auth-provisioning
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: postgres
automountServiceAccountToken: false
