apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-librechat-images
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "frontend-librechat.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.frontendLibrechat.app.imagePersistence.size }}
  {{- with .Values.frontendLibrechat.app.imagePersistence.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
