apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "frontend-librechat.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "frontend-librechat.labels" . | nindent 4 }}
automountServiceAccountToken: false
