apiVersion: v1
kind: Service
metadata:
  name: frontend-dify-web-gui-service
  namespace: frontend-dify
  labels:
    app.kubernetes.io/name: web-gui
    app.kubernetes.io/instance: frontend-dify-web-gui
    app.kubernetes.io/part-of: frontend-dify
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.frontendDify.webGui.ports.service.http }}
      targetPort: {{ .Values.frontendDify.webGui.ports.container.http }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: web-gui
    app.kubernetes.io/instance: frontend-dify-web-gui
