apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-dify-sandbox-pvc
  namespace: frontend-dify
  labels:
    app.kubernetes.io/name: sandbox
    app.kubernetes.io/instance: frontend-dify-sandbox
    app.kubernetes.io/part-of: frontend-dify
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.frontendDify.storage.dependenciesSize }}
  storageClassName: {{ .Values.frontendDify.storage.storageClassName }}
