apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: monitor-langfuse-langfuse-object-bucket-claim
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: langfuse-object-bucket-claim
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: monitor-langfuse
spec:
  bucketName: langfuse
  storageClassName: infra-rook-ceph-object-bucket
