apiVersion: v1
kind: ServiceAccount
metadata:
  name: infra-cert-manager-external-secrets
  namespace: infra-cert-manager
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: infra-cert-manager-secret-sync
    app.kubernetes.io/part-of: infra-cert-manager
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: infra-cert-manager-openbao-secret-store
  namespace: infra-cert-manager
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: infra-cert-manager-secret-sync
    app.kubernetes.io/part-of: infra-cert-manager
spec:
  provider:
    vault:
      server: https://infra-openbao.infra-openbao.svc:8200
      path: secret
      version: v2
      caProvider:
        type: ConfigMap
        name: infra-openbao-ca-bundle
        key: ca.crt
      auth:
        kubernetes:
          mountPath: kubernetes
          role: infra-cert-manager
          serviceAccountRef:
            name: infra-cert-manager-external-secrets
            audiences:
              - openbao
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager-issuers-values
  namespace: infra-cert-manager
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: infra-cert-manager-secret-sync
    app.kubernetes.io/part-of: infra-cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infra-cert-manager-openbao-secret-store
    kind: SecretStore
  target:
    name: cert-manager-issuers-values
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      type: Opaque
      metadata:
        labels:
          reconcile.fluxcd.io/watch: Enabled
      data:
        values.yaml: |
          certManager:
            aws:
              accessKeyId: {{ .accessKeyId | quote }}
              secretAccessKey: {{ .secretAccessKey | quote }}
  data:
    - secretKey: accessKeyId
      remoteRef:
        key: infra-cert-manager/external
        property: accessKeyId
    - secretKey: secretAccessKey
      remoteRef:
        key: infra-cert-manager/external
        property: secretAccessKey
