apiVersion: v1
kind: ServiceAccount
metadata:
  name: infra-postgres-auth-external-secrets
  namespace: infra-postgres-auth
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: infra-postgres-auth-secret-sync
    app.kubernetes.io/part-of: postgres
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: infra-postgres-auth-openbao-secret-store
  namespace: infra-postgres-auth
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: infra-postgres-auth-secret-sync
    app.kubernetes.io/part-of: postgres
spec:
  provider:
    vault:
      server: https://infra-openbao.infra-openbao.svc:8200
      path: secret
      version: v2
      caProvider:
        type: ConfigMap
        name: infra-openbao-ca-bundle
        key: ca.crt
      auth:
        kubernetes:
          mountPath: kubernetes
          role: infra-postgres-auth
          serviceAccountRef:
            name: infra-postgres-auth-external-secrets
            audiences:
              - openbao
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-auth-values
  namespace: infra-postgres-auth
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: infra-postgres-auth-secret-sync
    app.kubernetes.io/part-of: postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infra-postgres-auth-openbao-secret-store
    kind: SecretStore
  target:
    name: postgres-auth-values
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      type: Opaque
      metadata:
        labels:
          reconcile.fluxcd.io/watch: Enabled
      data:
        values.yaml: |
          postgresAuthSecrets:
            adminPassword: {{ .adminPassword | quote }}
            keycloakPassword: {{ .keycloakPassword | quote }}
  data:
    - secretKey: adminPassword
      remoteRef:
        key: infra-postgres-auth/internal
        property: adminPassword
    - secretKey: keycloakPassword
      remoteRef:
        key: infra-postgres-auth/internal
        property: keycloakPassword
