apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - auth-keycloak.yaml
  - auth-keycloak-api-key-bridge.yaml
  - frontend-dify.yaml
  - frontend-librechat.yaml
  - librechat-code-interpreter.yaml
  - frontend-studio.yaml
  - infra-agentgateway.yaml
  - infra-cert-manager.yaml
  - infra-postgres-auth.yaml
  - infra-postgres-operations.yaml
  - monitor-fluent-bit.yaml
  - monitor-kube-prometheus-stack.yaml
  - monitor-langfuse.yaml
  - monitor-opensearch.yaml
  - monitor-pii-engine.yaml
