apiVersion: v2
name: librechat-code-interpreter-api
description: Internal LibreChat Code Interpreter API backed by BullMQ
type: application
version: 0.1.0
appVersion: "fea707467600f3802d65596a6875c7822f25cfd8"
annotations:
  source.commit: fea707467600f3802d65596a6875c7822f25cfd8
  source.repository: https://github.com/ClickHouse/code-interpreter
