apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: docling
resources:
  - app.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: base-shared-document-attachments-config-map
    files:
      - values.yaml=../../shared/document-attachments.yaml
  - name: docling-app-defaults
    files:
      - values.yaml=app-defaults.yaml
